<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stock[
<!ELEMENT stock (new-car | used-car)*>
<!ELEMENT new-car (model, price)>
<!ELEMENT used-car (model, price, mileage, condition?)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT mileage (#PCDATA)>
<!ELEMENT condition (#PCDATA)>
]>

<stock>
  <new-car>
    <model>Lamborghini Sesto Elemento</model>
    <price>2'5 millones de euros</price>
  </new-car>
  <new-car>
    <model>Lexus LFA</model>
    <price>380.000 euros</price>
  </new-car>
  <used-car>
    <model>Ssangyong Rodius</model>
    <price>5.300 euros</price>
    <mileage>120.000 kil√≥metros</mileage>
    <condition>Muy buen estado</condition>
  </used-car>
</stock>
