<?xml version="1.0" encoding="UTF-8">
<!DOCTYPE lettera[
<!ELEMENT lettera (cliente,ordine,responsabile,mensaje?)>
<!ATTLIST lettera
  comments CDATA #IMPLIED>
<!ELEMENT cliente (#PCDATA)>
<!ELEMENT ordine (articolo+)>
<!ATTLIST ordine
  num ID #REQUIRED>
<!ELEMENT articolo (codice,descr)>
<!ELEMENT codice (#PCDATA)>
<!ELEMENT descr (#PCDATA)>
<!ELEMENT responsabile (tit)>
<!ELEMENT tit (#PCDATA)>
]>

<lettera>
  Gentile <cliente> tal dei tali </cliente>,
  la informiamo che i seguenti articoli da lei ordinati non sono pi√π disponibili a magazzino:
  <ordine num="1234">
    <articolo>
      <codice>1</codice>
      <descr>articolo 1</descr>
    </articolo>
    <articolo>
      <codice>5</codice>
      <descr>articolo 5</descr>
    </articolo>
  </ordine>
  Cordial saluti
  <responsabile><tit>dr.</tit>Mario Rossi</responsabile>
</lettera>
